export const countryByCode = {
	af: 'Afghanistan',
	az: 'Azerbaijan',
	bh: 'Bahrain',
	bd: 'Bangladesh',
	bt: 'Bhutan',
	bn: 'Brunei',
	kh: 'Cambodia',
	cn: 'China',
	cy: 'Cyprus',
	ge: 'Georgia',
	in: 'India',
	id: 'Indonesia',
	ir: 'Iran',
	iq: 'Iraq',
	is: 'Israel',
	jp: 'Japan',
	jo: 'Jordan',
	kz: 'Kazakhstan',
	kp: 'North Korea',
	kr: 'South Korea',
	kw: 'Kuwait',
	kg: 'Kyrgyzstan',
	la: 'Laos',
	lb: 'Lebanon',
	mo: 'Macau',
	my: 'Malaysia',
	mv: 'Maldives',
	mn: 'Mongolia',
	mm: 'Myanmar',
	np: 'Nepal',
	om: 'Oman',
	pk: 'Pakistan',
	ph: 'Philippines',
	qa: 'Qatar',
	sa: 'Saudi Arabia',
	sg: 'Singapore',
	lk: 'Sri Lanka',
	sy: 'Syria',
	tj: 'Tajikistan',
	th: 'Thailand',
	tr: 'Turkey',
	tm: 'Turkmenistan',
	ae: 'United Arab Emirates',
	uz: 'Uzbekistan',
	vn: 'Vietnam',
	ye: 'Yemen',
} as { [key: string]: string }
